const verses = [
    "Psalm 68:7 - Den Einsamen gibt er ein Zuhause, den Gefangenen schenkt er Freiheit und Glück",
    "Psalm 54:6 - Aber ich weiss: Gott ist mein Helfer, der Herr setzt sich stets für mich ein",
    "Psalm 62:2 - Bei Gott allein findet meine Seele Ruhe, von ihm kommt meine Hilfe",
    "Philliper 2:10-11 - Damit in dem Namen Jesu jedes Knie sich beuge, der Himmlischen und Irdischen und Unterirdischen, und jede Zunge bekenne, dass Jesus Christus der Herr ist",
    "Philliper 4:13 - Alles vermag ich durch Jesus Christus, der mich stärkt",
    "Lukas 1:37 - Denn für Gott ist nichts unmöglich"
    "Romans 10:13 - Indeed, 'everyone who calls on the name of the Lord will be saved.'",
"Matthew 11:30 - For my yoke is easy and my burden is light.",
"Matthew 6:27 - Can any one of you by worrying add a single hour to your life?",
"Galatians 6:5 - For everyone has his own burden to bear.",
"Proverbs 30:5 - Every word of God proves true; he is a shield to those who take refuge in him.",
"1 Peter 5:7 - Casting all your anxieties on him, because he cares for you.",
"Psalm 145:9 - The LORD is good to all; he has compassion on all he has made.",
"Psalm 23:1 - The Lord is my shepherd, I lack nothing.",
"Hebrews 12:29 - For our God is a consuming fire.",
"Ecclesiastes 3:1 - For everything there is a season, and a time for every matter under heaven.",
"Psalm 118:24 - This is the day that the Lord has made; let us rejoice and be glad in it.",
"Isaiah 26:4 - Trust in the Lord forever, for the Lord God is an everlasting rock.",
"Proverbs 18:10 - The name of the LORD is a fortified tower; the righteous run to it and are safe.",
"1 Corinthians 10:31 - So whether you eat or drink or whatever you do, do it all for the glory of God.",
"Psalm 37:4 - Take delight in the LORD, and he will give you the desires of your heart.",
"Lamentations 3:23 - They are new every morning; great is your faithfulness.",
"John 10:30 - I and the Father are one.",
"Genesis 1:1 - In the beginning, God created the heavens and the earth.",
"Romans 3:23 - For all have sinned and fall short of the glory of God.",
"Deuteronomy 5:7 - You shall have no other gods besides me.",
"Matthew 22:14 - For many are invited, but few are chosen.",
"John 1:4 - In him was life, and that life was the light of all mankind.",
"Colossians 3:3 - For you died, and your life is now hidden with Christ in God.",
"1 John 4:19 - We love because he first loved us.",
"Proverbs 27:17 - As iron sharpens iron, so one person sharpens another.",
"Matthew 6:12 - And forgive us our debts, as we also have forgiven our debtors.",
"Matthew 22:39 - Love your neighbor as yourself.",
"1 John 4:8 - Whoever does not love does not know God, because God is love.",
"1 John 5:3 - In fact, this is love for God: to keep his commands. And his commands are not burdensome.",
"Proverbs 10:12 - Hatred stirs up conflict, but love covers over all wrongs.",
"Psalm 136:1 - Give thanks to the Lord, for he is good. His love endures forever.",
"1 Corinthians 13:4 - Love is patient, love is kind. It does not envy, it does not boast, it is not proud.",
"Psalm 63:3 - Because your love is better than life, my lips will glorify you.",
"John 15:12 - My command is this: Love each other as I have loved you.",
"Romans 12:9 - Love must be sincere. Hate what is evil; cling to what is good.",
"Hebrews 11:1 - Now faith is confidence in what we hope for and assurance about what we do not see.",
"James 2:17 - So also faith by itself, if it does not have works, is dead.",
"Luke 17:5 - The apostles said to the Lord, 'Increase our faith.'",
"2 Corinthians 5:7 - For we walk by faith, not by sight.",
"Matthew 21:22 - Whatever you ask for in faith-filled prayer, you will receive.",
"James 2:24 - You can see, then, that a man is justified by works and not by faith alone.",
"James 1:3 - For you know that the testing of your faith will develop perseverance.",
"John 15:14 - You are my friends if you do what I command.",
"Matthew 5:14 - You are the light of the world.",
"Hebrews 13:8 - Jesus Christ is the same yesterday and today and forever.",
"Psalm 25:1 - In you, Lord my God, I put my trust.",
"Romans 12:12 - Be joyful in hope, patient in affliction, faithful in prayer.",
"Psalm 120:1 - I call on the Lord in my distress, and he answers me.",
"Psalm 150:6 - Let everything that has breath praise the Lord. Praise the Lord.",
"Romans 7:22 - For in my inner being, I delight in God’s law.",
"2 Timothy 4:7 - I have fought the good fight, I have finished the race, I have kept the faith.",
"1 Corinthians 2:5 - So that your faith might not rest on human wisdom, but on God’s power.",
"1 Timothy 6:6 - But godliness with contentment is great gain.",
"John 6:47 - Very truly I tell you, the one who believes has eternal life.",
"Psalm 119:30 - I have chosen the way of faithfulness; I have set my heart on your laws.",
"Romans 10:17 - So faith comes from hearing, and hearing through the word of Christ.",
"Luke 6:31 - Do to others as you would have them do to you.",
"Matthew 7:1 - Do not judge, or you too will be judged.",
"Luke 6:36 - Be merciful, just as your Father is merciful.",
"Deuteronomy 5:20 - You shall not give false testimony against your neighbor.",
"Proverbs 15:1 - A gentle reply turns away wrath, but a harsh word arouses anger.",
"Ephesians 4:32 - Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you.",
"Proverbs 17:13 - Evil will never leave the house of one who pays back evil for good.",
"Proverbs 17:17 - A friend loves at all times, and a brother is born for a time of adversity.",
"John 15:13 - Greater love has no one than this: to lay down one’s life for one’s friends.",
"John 11:35 - Jesus wept.",
"1 Thessalonians 5:17 - Pray without ceasing.",
"1 Thessalonians 5:16 - Rejoice always.",
"1 Corinthians 16:14 - Do everything in love.",
"Luke 17:32 - Remember Lot’s wife!",
"Exodus 20:15 - You shall not steal.",
"Exodus 20:13 - You shall not murder.",
"Proverbs 2:6 - For the Lord gives wisdom; from his mouth come knowledge and understanding.",
"Numbers 6:24 - The Lord bless you and keep you.",
"Luke 1:37 - For nothing will be impossible for God.",
"Proverbs 14:5 - An honest witness does not lie, a false witness breathes lies.",
"Philippians 2:14 - Do everything without grumbling or arguing.",
"Psalm 25:4 - Show me your ways, Lord, teach me your paths.",
"Proverbs 3:5 - Trust in the Lord with all your heart and lean not on your own understanding.",
"Psalm 37:5 - Commit your way to the Lord; trust in him, and he will act.",
"Colossians 3:2 - Set your mind on things above, not on earthly things.",
"Colossians 3:20 - Children, obey your parents in all things.",
"Psalm 56:3 - When I am afraid, I put my trust in you.",
"1 Thessalonians 5:22 - Reject every kind of evil.",
"Hebrews 13:25 - Grace be with you all.",
"Proverbs 27:24 - For riches do not last forever, nor will a crown endure from age to age.",
"Psalm 119:105 - Your word is a lamp for my feet, a light on my path.",
"Romans 10:11 - Anyone who believes in him will never be put to shame.",
"1 John 5:21 - Dear children, keep yourselves from idols.",
"Exodus 20:8 - Remember the Sabbath day by keeping it holy.",
"John 3:30 - He must become greater; I must become less.",
"Proverbs 20:22 - Do not say, 'I will repay evil'; wait for the Lord, and he will deliver you.",
"Proverbs 15:22 - Plans fail for lack of counsel, but with many advisers they succeed.",
"Isaiah 40:29 - He strengthens those who are weak and tired."
  ];
  
  function displayRandomVerse() {
    const randomIndex = Math.floor(Math.random() * verses.length);
    const randomVerse = verses[randomIndex];
    alert(randomVerse);
  }
  
  document.getElementById('randomButton').addEventListener('click', displayRandomVerse);
  
